# Generated by Django 4.1.7 on 2023-08-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_clinic_service_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='Clinic Service/')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='service',
            field=models.ManyToManyField(to='main.service'),
        ),
    ]
